#pragma once

#include <memory>
#include <vector>
#include <unordered_map>
#include <typeinfo>
#include <typeindex>
#include <functional>
#include <future>
#include <algorithm>
#include <array>
#include <unordered_set>
#include <sstream>
#include <map>
#include <set>
#include <array>
#include <stdio.h>
#include <string>
#include <stdexcept>
#include <thread>	
#include <mutex>
#include <shared_mutex>
#include <xtr1common>
#include <variant>
#include <utility>
#include <type_traits>
#include <tuple>
#include <iostream>
#include <fstream>
#include <stdlib.h>

#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <glad/glad.h>